# Generated by Django 3.2.1 on 2021-05-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='body',
            new_name='Diary',
        ),
    ]
