# Generated by Django 3.2.1 on 2021-05-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_rename_body_diary_diary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='Diary',
            new_name='body',
        ),
    ]
